= EIA Data Profile

This repository contains the source data for the EIA Data Profile which is a _profile_ of the https://linked.data.gov.au/def/loci-dp[Loci-I Data Profile].

This profile is published online at:

* **https://linked.data.gov.au/def/eia-dp**

== Content

The main content of this repository is:

|===
| **Resource**           | **Role**                                                           | **Location**

| Profile Definition     | definition                                                         | `profile.ttl`
| Specification Document | https://www.w3.org/TR/dx-prof/#Role:specification[specification] | `specification.html`
| SHACL Validator        | https://www.w3.org/TR/dx-prof/#Role:validation[validation]       | `validation.ttl`
| Examples               | https://www.w3.org/TR/dx-prof/#Role:example[example]             | `examples/`
|===

== License & Citation

The contents of this repository are licensed using the https://creativecommons.org/licenses/by/4.0/[CC BY 4.0] licence. See the [LICENSE file](LICENSE) for the deed.

The citation for this profile is:

&copy; Department of Climate Change, Energy, the Environment and Water, 2025

== Contact

**contact:** +
https://www.dcceew.gov.au/environment/environment-information-australia/biodiversity-data-repository[Biodiversity Data Repository Team] +
bdr@dcceew.gov.au +

**publisher:** +
Environment Information Australia +
https://www.dcceew.gov.au[Department of Climate Change, Energy, the Environment and Water] +
eia.feedback@dcceew.gov.au +

**creator:** +
https://kurrawong.ai[KurrawongAI] +
info@kurrawong.ai +
https://orcid.org/0000-0002-8742-7730 +