== Introduction

This "data profile" is a profile of the <<LOCIDP, _Loc-I Data Profile_>> is, in turn, a profile of several well-known https://en.wikipedia.org/wiki/Semantic_Web[Semantic Web] data standards.

* A **_profile_** is a "specification that constrains, extends, combines, or provides guidance or explanation about the usage of other specifications" https://www.w3.org/TR/dx-prof/#dfn-data-specification[[W3C]].

The <<LOCIDP, _Loc-I Data Profile_>> sets requirements for two main, and generic, dimensions of datasets:

* data management
* spatio/temporal

Data cannot reasonably be managed unless the "data management" dimensions of it are organised and the standardisation of the spatio/temporal dimension is also fundamental for data about the earth and environment, as EIA data is.

The <<LOCIDP, _Loc-I Data Profile_>> essentially marries up these two dimensions to prescribe how to package and describe (with metadata), spatial datasets. The particular elements of standardisation that it uses in each dimension, it inherits from the standards it profiles, for example:

* for **data management**: <<SDO, schema.org>>, basic metadata such as name, license etc.
* for **spatio/temporal**: <<GSP, GeoSPARQL>>, spatial objects such as Features and Geometries

This profile builds on the <<LOCIDP, _Loc-I Data Profile_>> to introduce the following:

* for **data management**: <<PROJ, BDR Project Model>>, information about projects that relate to data
* for the **environment** dimension:
** <<SOSA, SOSA Ontology>>, observations & measurements modelling
** <<NSLM, National Species List Model>>, species' names & taxa

[#intro-data-dimensions,link="img/dimensions.svg"]
.The main dimensions of data constrained by this profile
image::img/dimensions.svg[Data dimensions,align="center",width=400]

=== Multiple Models

This profile not only profiles the <<LOCIDP, _Loc-I Data Profile_>> but other models too, such as <<SOSA, SOSA Ontology>> and the <<PROJ, BDR Project Model>>.

Since the <<LOCIDP, _Loc-I Data Profile_>> also profiles other models such as <<GSP, GeoSPARQL>>, we have a dependency pyramid of multiple models needed for this profile to work.

The relation of this profile to the <<LOCIDP, _Loc-I Data Profile_>> and the other models it directly profiles are defined in this profile's technically definition however the things transitively profiled by this model are not necessarily indicated there. Instead, these other models are all described and related in the https://linked.data.gov.au/def/eia-supermodel[EAI Supermodel] which is an enterprise data model.

=== Governance

This Profile is governed by the BDR Team, see the _Contacts_ in the <<Metadata, Medata Section>> above.

Currently, governance of this profile is by the BDR Team only but this may change if this profile becomes widely used.

=== Structure

#up to here#

This specification aims to cover all the information needed to understand ABIS and use it. The following is a list of the major sections in this document and their purposes.

[start=4]
. <<Introduction, Introduction>>
** This section. An informal overview of ABIS
. <<ABIS Constraints, ABIS Constraints>>
** Constraints that this profile places on the use of ABIS
. <<Models, Models>>
** The normative description of the models this profile uses in addition to ABIS
. <<Vocabularies, Vocabularies>>
** Description of, and links to, the vocabularies needed for use with ABIS
. <<Validation, Validation>>
** How to validate data according to ABIS and links to the various validators

Four additional models are defined in this Profile and detailed as Annexes in this document:

* <<annex-a, Annex A: Projects Model>>
* <<annex-b, Annex B: Data Release Model>>
* <<annex-c, Annex C: Submission Manifest Model>>

Extended examples are given in <<annex-d, Annex D: Extended Examples>>.
