== Introduction

This "data profile" is a profile of the <<LOCIDP, _Loc-I Data Profile_>> is, in turn, a profile of several well-known https://en.wikipedia.org/wiki/Semantic_Web[Semantic Web] data standards.

* A **_profile_** is a "specification that constrains, extends, combines, or provides guidance or explanation about the usage of other specifications" https://www.w3.org/TR/dx-prof/#dfn-data-specification[[W3C]].

The <<LOCIDP, _Loc-I Data Profile_>> sets requirements for two main, and generic, dimensions of datasets:

* data management
* spatio/temporal

Data cannot reasonably be managed unless the "data management" dimensions of it are organised and the standardisation of the spatio/temporal dimension is also fundamental for data about the earth and environment, as EIA data is.

The <<LOCIDP, _Loc-I Data Profile_>> essentially marries up these two dimensions to prescribe how to package and describe (with metadata), spatial datasets. The particular elements of standardisation that it uses in each dimension, it inherits from the standards it profiles, for example:

* for **data management**: <<SDO, schema.org>>, basic metadata such as name, license etc.
* for **spatio/temporal**: <<GSP, GeoSPARQL>>, spatial objects such as Features and Geometries

This profile builds on the <<LOCIDP, _Loc-I Data Profile_>> to introduce the following:

* for **data management**: <<PROJ, BDR Project Model>>, information about projects that relate to data
* for the **environment** dimension:
** <<SOSA, SOSA Ontology>>, observations & measurements modelling
** <<NSLM, National Species List Model>>, species' names & taxa

[#intro-data-dimensions,link="img/dimensions.svg"]
.The main dimensions of data constrained by this profile
image::img/dimensions.svg[Data dimensions,align="center",width=400]

=== Multiple Models

This profile not only profiles the <<LOCIDP, _Loc-I Data Profile_>> but other models too, such as <<SOSA, SOSA Ontology>> and the <<PROJ, BDR Project Model>>. Since the <<LOCIDP, _Loc-I Data Profile_>> also profiles other models such as <<GSP, GeoSPARQL>>, we have a dependency pyramid of multiple models needed for this profile to work. The profile hierarchy of this profile is given in the figure below.

[#profile-hierarchy,link="img/profile-hierarchy.svg"]
.The Profile Hierarchy of this Profile. The other models shown in the figure are all references in this Profile: <<GSP, GeoSPARQL>>, <<SDO, schema.org>>, <<PROV, PROV>>, <<SOSA, SOSA>>, <<TIME, Time ontology in OWL>>, <<LOCIDP, Loci-I DP>>, <<PROJ, BDR Project Model>>, <<ANSISO, ANSIS Ontology>>, <<NSLM, NSL Model>>.
image::img/profile-hierarchy.svg[The Profile Hierarchy of this Profile,align="center",width=700]

The relation of this profile to the <<LOCIDP, _Loc-I Data Profile_>> and the other models it directly profiles are defined in this profile's technically definition however the things transitively profiled by this Profile are not necessarily indicated there. Instead, you may have to view the directly profiling entity's information for details. Note that the https://linked.data.gov.au/def/eia-supermodel[EAI Supermodel], an enterprise data model that uses this Profile, contains a complete picture of all things profiled by this Profile too.

=== Governance

This Profile is governed by the BDR Team, see the _Contacts_ in the <<Metadata, Medata Section>> above.

Currently, governance of this profile is by the BDR Team only but this may change if this profile becomes widely used.

=== Structure

This specification aims to cover all the information needed to understand this Profile and use it. The following is a list of the major sections in this document and their purposes.

[start=4]
. <<Introduction, Introduction>>
** This section. An informal overview of the Profile
. <<Specification, Specification>>
** The formal specification of requirements on data to conform to this Profile
** Requirements are defined in English (narrative) and corresponding Semantic Web definitions are given
. <<Vocabularies, Vocabularies>>
** Description of, and links to, the vocabularies needed for use with this Profile
. <<Validation, Validation>>
** How to validate data according to this Profile and links to the various validators


Extended examples are given in <<annex-a, Annex X: Extended Examples>>.
