== Vocabularies

For data to conform to the BDR Profile of ABIS, many vocabularies must be used. Some of the vocabularies are required for use by ABIS - lists of measurement techniques, feature types etc. - others must be used for metadata values for ABIS objects. ABIS objects' metadata may require values such as "creator" for agent roles which the underlying TERN Ontology do not constrain, only requiring that some value be present and likewise, this profile may require particular values that ABIS does not constrain.

There are also elements of the models defined in this Profile that must be used with vocabularies, such as the <<annex-c, Submission Manifest Model>>'s `hasRole` predicate which must indicate a value from the <<#_bdr_submission_manifest_resource_roles, Submission Manifest Resource Roles vocabulary>>.

=== Finding the vocabularies

All the vocabularies needed for use with this Profile, including ABIS and its background models, are listed within the https://bdr.gov.au[BDR Portal]'s catalogue section:

* https://bdr.gov.au/catalogues

